name: Run Tests with pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # يُفترض أن ملف requirements.txt يحتوي على pytest أو يجب تثبيته هنا بشكل صريح
        # مثال: pip install -r requirements.txt pytest

    - name: Run tests with pytest
      run: |
        pytest Tests/test_login.py
